# Generated by Django 5.2.4 on 2025-09-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('name', models.CharField(help_text='Up to 5 letters, upper-case letters + numbers', max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60)),
                ('long_description', models.CharField(max_length=600)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('public', models.BooleanField(default=False, help_text='Publicly available on the order page')),
                ('start_date', models.DateField(blank=True, help_text='Available on this day', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Not Usable on this day', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(help_text='Unique, up to 4 upper-case letters / numbers', max_length=4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60)),
                ('long_description', models.CharField(max_length=600)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('active', models.BooleanField(default=False)),
                ('promo', models.BooleanField(default=False, help_text='Price affected by promo code?')),
                ('package_offset', models.BooleanField(default=False, help_text='Item offsets package price?')),
                ('applies_to_all', models.BooleanField(default=False, help_text='Applies to all packages')),
                ('applies_to', models.ManyToManyField(blank=True, to='sponsorship.package')),
            ],
        ),
    ]
