# Generated by Django 5.2.4 on 2025-11-17 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0002_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=False)),
                ('salutation', models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Ms', 'Ms.'), ('Mrs', 'Mrs.'), ('Dr', 'Dr.')], max_length=10)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('title', models.CharField(blank=True, max_length=60)),
                ('org', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('agreed', models.BooleanField(default=False)),
                ('ordered_items', models.ManyToManyField(blank=True, to='sponsorship.item')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsorship.package')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sponsorship.promocode')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_num', models.CharField(help_text='Unique 10 upper-case letters + numbers code', max_length=10, primary_key=True, serialize=False)),
                ('valid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payflow_auth_code', models.CharField(blank=True, max_length=30)),
                ('payflow_pnref', models.CharField(blank=True, max_length=15)),
                ('payflow_resp_msg', models.CharField(blank=True, max_length=60)),
                ('payflow_result', models.CharField(blank=True, max_length=60)),
                ('already_paid_sponsor', models.BooleanField(default=False)),
                ('sponsor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sponsorship.sponsor')),
            ],
        ),
    ]
