# Generated by Django 5.2.4 on 2025-11-22 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0003_sponsor_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('order_num', models.CharField(help_text='Unique 10 upper-case letters + numbers code', max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsorship.sponsor')),
            ],
        ),
    ]
