# Generated by Django 5.2.9 on 2026-01-17 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0004_pendingorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sponsor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sponsorship.sponsor'),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorship.sponsor'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorship.package'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorship.promocode'),
        ),
    ]
