# Generated by Django 5.2.4 on 2025-07-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('name', models.CharField(help_text='Up to 5 letters, upper-case letters + numbers', max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60)),
                ('ticket_type', models.CharField(choices=[('exhibitor', 'Exhibitor'), ('expo', 'Expo Only'), ('full', 'Full'), ('kid', 'Kids Pass'), ('press', 'Press'), ('speaker', 'Speaker'), ('staff', 'Staff')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('public', models.BooleanField(help_text='Publicly available on the order page')),
                ('cash', models.BooleanField(help_text='Available for cash purchase')),
                ('upgradable', models.BooleanField(help_text='Eligible for upgrades')),
                ('start_date', models.DateField(blank=True, help_text='Available on this day', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Not Usable on this day', null=True)),
            ],
        ),
    ]
