# Generated by Django 5.2.4 on 2025-07-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(help_text='Unique, up to 4 upper-case letters / numbers', max_length=4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField()),
                ('promo', models.BooleanField(help_text='Price affected by promo code?')),
                ('ticket_offset', models.BooleanField(help_text='Item offsets ticket price?')),
                ('applies_to_all', models.BooleanField(help_text='Applies to all tickets')),
                ('applies_to', models.ManyToManyField(blank=True, to='reg23.ticket')),
            ],
        ),
    ]
