# Generated by Django 5.2.4 on 2025-07-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('name', models.CharField(help_text='Up to 5 letters, upper-case letters + numbers', max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60)),
                ('price_modifier', models.DecimalField(decimal_places=2, help_text='This is the price multiplier, i.e. for 0.4, $10 becomes $4.', max_digits=3)),
                ('active', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, help_text='Available on this day', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Not Usable on this day', null=True)),
                ('applies_to_all', models.BooleanField(default=False, help_text='Applies to all tickets')),
                ('applies_to', models.ManyToManyField(blank=True, to='reg23.ticket')),
            ],
        ),
    ]
