# Generated by Django 5.2.4 on 2025-08-04 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0003_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=False)),
                ('checked_in', models.BooleanField(default=False, help_text='Only for valid attendees')),
                ('salutation', models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Ms', 'Ms.'), ('Mrs', 'Mrs.'), ('Dr', 'Dr.')], max_length=10)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('title', models.CharField(blank=True, max_length=60)),
                ('org', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('can_email', models.BooleanField(default=False)),
                ('badge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reg23.ticket')),
                ('ordered_items', models.ManyToManyField(blank=True, to='reg23.item')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reg23.promocode')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_num', models.CharField(help_text='Unique 10 upper-case letters + numbers code', max_length=10, primary_key=True, serialize=False)),
                ('valid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_type', models.CharField(choices=[('payflow', 'Payflow'), ('cash', 'Cash'), ('invitee', 'Invitee'), ('exhibitor', 'Exhibitor'), ('speaker', 'Speaker'), ('press', 'Press'), ('freeup', 'Free Upgrade')], max_length=10)),
                ('payflow_auth_code', models.CharField(blank=True, help_text='Only used by Payflow', max_length=30)),
                ('payflow_pnref', models.CharField(blank=True, help_text='Payment Network Reference ID (PNREF), a number generated by Payment that uniquely identifies the transaction', max_length=15)),
                ('payflow_resp_msg', models.CharField(blank=True, help_text='Only used by Payflow', max_length=60)),
                ('payflow_result', models.CharField(blank=True, help_text='Only used by Payflow', max_length=60)),
                ('already_paid_attendees', models.ManyToManyField(blank=True, help_text='Attendees charged multiple times on this order', related_name='already_paid', to='reg23.attendee')),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reg23.order'),
        ),
    ]
