# Generated by Django 5.2.4 on 2025-08-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0004_attendee_order_attendee_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('order_num', models.CharField(help_text='Unique 10 upper-case letters + numbers code', max_length=10, primary_key=True, serialize=False)),
                ('attendees', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
