# Generated by Django 5.2.4 on 2025-08-31 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0005_pendingorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='answers',
            field=models.ManyToManyField(blank=True, to='reg23.answer'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('applies_to_all', models.BooleanField(default=False, help_text='Applies to all tickets')),
                ('is_text_question', models.BooleanField(default=False, help_text='False for list question')),
                ('max_length', models.IntegerField(blank=True, help_text='Only for text questions', null=True)),
                ('applies_to_items', models.ManyToManyField(blank=True, to='reg23.item')),
                ('applies_to_tickets', models.ManyToManyField(blank=True, to='reg23.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reg23.question'),
        ),
    ]
