# Generated by Django 5.2.4 on 2025-10-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0006_answer_attendee_answers_question_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
