# Generated by Django 5.2.4 on 2025-12-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0007_item_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='can_email',
            field=models.IntegerField(choices=[(0, 'Logistics Only'), (1, 'Announcements'), (2, 'Special Offers')], default=0),
        ),
    ]
