# Generated by Django 5.2.9 on 2026-01-05 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0008_alter_attendee_can_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCode',
            fields=[
                ('code', models.CharField(help_text='Unique 10 upper-case letters + numbers code', max_length=10, primary_key=True, serialize=False)),
                ('max_attendees', models.PositiveSmallIntegerField()),
                ('badge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reg23.ticket')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reg23.order')),
            ],
        ),
    ]
