# Generated by Django 5.2.9 on 2026-01-17 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0009_paymentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg23.question'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='badge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg23.ticket'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg23.order'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg23.promocode'),
        ),
        migrations.AlterField(
            model_name='paymentcode',
            name='badge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg23.ticket'),
        ),
        migrations.AlterField(
            model_name='paymentcode',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg23.order'),
        ),
    ]
