# Generated by Django 5.2.9 on 2026-01-18 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0010_alter_answer_question_alter_attendee_badge_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg23.attendee')),
                ('new_badge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg23.ticket')),
                ('new_items', models.ManyToManyField(blank=True, to='reg23.item')),
                ('new_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg23.order')),
                ('old_badge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_badge_type', to='reg23.ticket')),
                ('old_items', models.ManyToManyField(blank=True, related_name='old_items', to='reg23.item')),
                ('old_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_order', to='reg23.order')),
            ],
        ),
    ]
