# Generated by Django 5.2.9 on 2026-01-25 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0011_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='upgrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg23.upgrade'),
        ),
    ]
