# Generated by Django 5.2.9 on 2026-02-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0012_pendingorder_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='kiosk_agent',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
