# Generated by Django 5.2.9 on 2026-02-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0013_attendee_kiosk_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='reprint_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
