# Generated by Django 5.2.9 on 2026-02-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0014_attendee_reprint_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='secondary_badge_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_badge', to='reg23.ticket'),
        ),
    ]
