# Generated by Django 5.2.9 on 2026-02-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0015_attendee_secondary_badge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('exhibitor', 'Exhibitor'), ('expo', 'Expo Only'), ('full', 'Full'), ('kid', 'Kids Pass'), ('press', 'Press'), ('speaker', 'Speaker'), ('staff', 'Staff'), ('volunteer', 'Volunteer')], max_length=10),
        ),
    ]
