# Generated by Django 5.2.9 on 2026-02-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0016_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='tshirt',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
