# Generated by Django 5.2.9 on 2026-02-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg23', '0017_attendee_tshirt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('kiosk_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
    ]
