# Generated by Django 5.2.2 on 2025-06-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg6', '0002_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(help_text='Ordering priority, lower numbers first'),
        ),
    ]
