# Generated by Django 5.2.2 on 2025-06-10 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('name', models.CharField(help_text='Up to 5 letters, upper-case letters + numbers', max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60)),
                ('long_description', models.CharField(max_length=600)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('public', models.BooleanField(default=False, help_text='Publicly available on the order page')),
                ('start_date', models.DateField(blank=True, help_text='Available on this day', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Not Usable on this day', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique, up to 4 upper-case letters / numbers', max_length=4)),
                ('description', models.CharField(max_length=60)),
                ('long_description', models.CharField(max_length=600)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('active', models.BooleanField(default=False)),
                ('promo', models.BooleanField(default=False, help_text='Price affected by promo code?')),
                ('package_offset', models.BooleanField(default=False, help_text='Item offsets package price?')),
                ('applies_to_all', models.BooleanField(default=False, help_text='Applies to all packages')),
                ('applies_to', models.ManyToManyField(blank=True, to='sponsorship.package')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('name', models.CharField(help_text='Up to 5 letters, upper-case letters + numbers', max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60)),
                ('price_modifier', models.DecimalField(decimal_places=2, help_text='This is the price multiplier, i.e. for 0.4, $10 becomes $4.', max_digits=3)),
                ('active', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, help_text='Available on this day', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Not Usable on this day', null=True)),
                ('applies_to_all', models.BooleanField(default=False, help_text='Applies to all packages')),
                ('applies_to', models.ManyToManyField(blank=True, to='sponsorship.package')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=False)),
                ('salutation', models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Ms', 'Ms.'), ('Mrs', 'Mrs.'), ('Dr', 'Dr.')], max_length=10)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('title', models.CharField(blank=True, max_length=60)),
                ('org', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('agreed', models.BooleanField(default=False)),
                ('ordered_items', models.ManyToManyField(blank=True, to='sponsorship.item')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorship.package')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorship.promocode')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_num', models.CharField(help_text='Unique 10 upper-case letters + numbers code', max_length=10, primary_key=True, serialize=False)),
                ('valid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('auth_code', models.CharField(blank=True, max_length=30)),
                ('pnref', models.CharField(blank=True, max_length=15)),
                ('resp_msg', models.CharField(blank=True, max_length=60)),
                ('result', models.CharField(blank=True, max_length=60)),
                ('already_paid_sponsor', models.BooleanField(default=False)),
                ('sponsor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sponsorship.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='TempOrder',
            fields=[
                ('order_num', models.CharField(help_text='Unique 10 upper-case letters + numbers code', max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sponsorship.sponsor')),
            ],
        ),
    ]
